### ISSUE TITLE
UI and UX improvement

### ISSUE THREAD

**Issue by tognee** [OsmTravel/OsmGo#162]
Hello and thanks for developing this app, I was looking for something just like this.
However there are some issues with the UI and UX of the app. I can see that there are a lot of cards and FABs misused inside the project and the UX is not that great for a new user that doesn't know what button does what.

I am working [on my branch](https://github.com/tognee/OsmGo/tree/design-tognee) to fix these issues, I'm hoping I can get some feedback and merge my changes upstream. Also made a draft pull request (#163)

I will update this post with all the changes I do.
- [X] Main screen
- [X] Side menu
- [X] Settings page
- [X] About page
- [X] Read modal
- [X] Edit modal

# Proposals
Here's what I already edited and it's available in my branch

## Side Menu
![immagine](https://user-images.githubusercontent.com/18465347/220576614-ab3035e8-4a7c-405c-a999-d9b5977ff75f.png)
There are two options with the same icon, changing one to actual tags should solve possible confusion.
![immagine](https://user-images.githubusercontent.com/18465347/220576781-1e6ea86f-2803-4472-b12d-22ab12028465.png)

## Settings
Currently the settings page uses a card for each option.
![immagine](https://user-images.githubusercontent.com/18465347/220572986-c58c74fd-2b0e-4ad0-bacf-ea1eb9b91d27.png)

Using as reference a default template of an app created with Android Studio I redesigned it to look more "native".
![immagine](https://user-images.githubusercontent.com/18465347/220573383-fd3a4586-04ad-438e-818e-5f1922dfb614.png)

Connected elements should act connected.
![immagine](https://user-images.githubusercontent.com/18465347/220573805-e92edd29-940c-4ea1-85ef-b8ef6243226c.png)
Disabling "Show an icon on old objects" should disable the option to move the slider. That explains to the user that the two options are connected with eachother.
![immagine](https://user-images.githubusercontent.com/18465347/220574093-7bd10e5f-664c-4edc-b4a0-038c01841731.png)
Same thing with the survey date tag.

## About
The current about page uses cards where it shouldn't.
![immagine](https://user-images.githubusercontent.com/18465347/220574530-3ba9e42b-9b5e-4201-8a73-900c52c1e57c.png)

Again with an app's about page in mind I redesigned it.
![immagine](https://user-images.githubusercontent.com/18465347/220574689-e802840c-40fd-45bd-9d16-cbbb12b6c66c.png)
I've added an app icon on the first item and the github logo to the github link. Also made the entire item clickable instead of just the text.

# Discussion
Here's what I would like to change in the app

## Main Screen
![immagine](https://user-images.githubusercontent.com/18465347/220575230-c2095335-ec0f-46f1-9e5f-cde30137d8f2.png)
The main screen is well designed and uses FABs as intended. The only issue is that some buttons are not that descriptive. The "Load Data" and "Satellite View" buttons are not intuitive on what they do until you press them. On desktop hovering on them just shows the name of the icon.
To solve this issue there should be an alt message for the icons or aria-labels for screen readers.

![immagine](https://user-images.githubusercontent.com/18465347/220577180-a9476833-4a38-4bc5-91ee-4079c0d0d26e.png)
When there are a lot of nodes on the screen the map can look so much noisy. There is already a modal that lets you pick from a group of overlapping nodes, it would be nice to have bigger circle with the number of nodes inside of it making the map look cleaner. When zooming in the single nodes would show instead.

## Read Modal
![immagine](https://user-images.githubusercontent.com/18465347/220578188-64efeaef-71da-494e-b71c-7bc8365b3c1f.png)
~The buttons at the bottom are misused FABs, they should be buttons instead.~ [**Fixed as described here**](https://github.com/OsmTravel/OsmGo/issues/162#issuecomment-1445127404)

The "Confirm add survey date" button is not descriptive and it's use is unknown until the button is pressed. An idea for a solution would be to remove the button from the footer and add a small card at the top of the page (under the metadata or primary key) that asks if the object is still there or if it's verified (wording can be defined later). This card would show up only if the last edit is older than the lapse of time set in the settings.
This way the button is labeled and it would not be present when it's not needed.
EDIT: I moved the button in the meta card component for now, needs a better implementation

## Edit Modal
![immagine](https://user-images.githubusercontent.com/18465347/220580273-11533487-2934-4843-bf19-25dfb170654d.png)
~The FABs at the bottom need to be made into buttons, as they are not floating.~ [**Fixed as described here**](https://github.com/OsmTravel/OsmGo/issues/162#issuecomment-1445127404)

The copy paste functionality at the top is not well explained and it's hard for a new user to understand it. Maybe changing it to undo and redo is more understandable?

~The favourite button is closer to the title of the node than to what its purpose really is, favouring the type of node.
The cogs icons next to the name of the tag seem useless, maybe the hearth icon could be put instead of the cog in the primary key card.~ [**Added as described here**](https://github.com/OsmTravel/OsmGo/issues/162#issuecomment-1443921444)

~When adding a new tag you need to know what to put inside the field, new users won't know what to do there. Adding a new modal with the list of possible tags (localized) could be helpful here, while keeping as an option adding a custom tag.~ [**Added as described here**](https://github.com/OsmTravel/OsmGo/issues/162#issuecomment-1466960829)

Some custom types inputs could be added like support for multiple tags (; separated) fields and an unified address input (but these can be added later on).

# Conclusion
If anyone else wants to add suggestions for these type of changes feel free to add them as comments below, so that together we can make this app better!

**Comment by tognee** [comment]
## Primary Key card
I have unified the read and edit components for PrimaryKey into a single component.

The design of the card is intact:
![immagine](https://user-images.githubusercontent.com/18465347/221228189-43004198-e76a-4e45-b282-16f233c27cc5.png)

When editing the node the card will show a hearth icon, when pressed it will turn red.
![immagine](https://user-images.githubusercontent.com/18465347/221228384-6bfa085b-2363-435d-8749-db84b615a062.png)
![immagine](https://user-images.githubusercontent.com/18465347/221228404-ae54cbed-db0a-4676-b49f-74a5870d5bea.png)

The icon, as well the text inside the card, is now centered vertically.
![immagine](https://user-images.githubusercontent.com/18465347/221228589-764676c0-2f8b-40db-ae91-4a2f2e37be63.png)

**Comment by tognee** [comment]
## Modal Footer
![immagine](https://user-images.githubusercontent.com/18465347/221360770-f3248bab-cc72-4d38-b44e-29f15ba60131.png)
In read mode we have the close button on the left and the edit button on the right

![immagine](https://user-images.githubusercontent.com/18465347/221360777-eb274df6-8675-4d02-9732-5ceb965a0caa.png)
In edit mode the edit button becomes the save changes button

![immagine](https://user-images.githubusercontent.com/18465347/221360887-53dfebbf-914c-40da-b36a-e39de36936a7.png)
![immagine](https://user-images.githubusercontent.com/18465347/221360954-280d07db-e4a0-4ce1-bfb0-8117eefc984b.png)
When editing a node or a line the move button and delete feature button appear on the center of the footer

![immagine](https://user-images.githubusercontent.com/18465347/221361067-a70404e2-42cd-415e-82ab-c328bd5ddeb1.png)
The "Confirm presence" button has been moved in the meta card. The meta card is only present in read mode as it's not a thing that you can edit.

![immagine](https://user-images.githubusercontent.com/18465347/221361070-c77ba816-d3c3-41f3-9038-5fc93d50ec97.png)
After this is pressed it will turn green and the last checked date field will be added.

![immagine](https://user-images.githubusercontent.com/18465347/221361104-2babe796-d2ee-46b1-91e7-dc6ac2de349f.png)
When there are changes applied on a node that aren't synced yet this banner will show. Here you will be able to clean the changes.

This section still needs translations and text near the buttons.
Some logic needs to be changed so that the modal will close only when the close button or the delete button is pressed.

**Comment by tognee** [comment]
## Opening hours

![immagine](https://user-images.githubusercontent.com/18465347/222198629-8c9a4809-48ef-4bd1-bb89-4506a54f242e.png)
The table is now occupying the whole card space
![immagine](https://user-images.githubusercontent.com/18465347/222198848-0b052660-02b8-4239-b45a-2ee2107ac080.png)
Same with the "Add Opening Hours" button while editing the node

![immagine](https://user-images.githubusercontent.com/18465347/222199542-d4341d76-5d51-490a-b754-1b96206f1e5f.png)
The page has been redesigned to look better. Each interval is now a card and the hours wheel actually works.
To keep all days in a single line I abbreviated them to 3 characters using a pipe (lenght can be changed in the template)

**Comment by tognee** [comment]
## Primary Key modal

![immagine](https://user-images.githubusercontent.com/18465347/224831097-67affea3-c780-453b-a7e7-845ca2d0cbf8.png)
This modal now uses the same style as the other redesigned tabs for the footer. Buttons now show which tab is selected and they use a style similar to actual tabs

**Comment by tognee** [comment]
## Add tag modal
![immagine](https://user-images.githubusercontent.com/18465347/224831807-19399998-04bc-4b99-ad2b-9b03bb910b62.png)
When clicking the add tag button in the edit view this new modal shows up. By default it shows all tags in the moreFields section (Reimplementing #119).

![immagine](https://user-images.githubusercontent.com/18465347/224832210-55dc456a-7a66-4d9e-b177-c81c196084ef.png)
The search bar on the top lets the user to search in all known presets by tag name or by localized name

![immagine](https://user-images.githubusercontent.com/18465347/224832579-dfd6d99e-99b5-4a73-99c2-8f73b9efec74.png)
When searching the first result will always be the actual input of the search bar, letting the user add custom tags

![immagine](https://user-images.githubusercontent.com/18465347/224832508-f901afe6-bf50-4a9a-a858-be8f393660c5.png)
If a tag key matches 100% it will be shown as the first element of the list

![immagine](https://user-images.githubusercontent.com/18465347/224832811-70a907f7-7b4c-4963-bd3d-80a52ea9bd19.png)
If a tag is already present in the edited feature it will not show up in the results

**Comment by DoFabien** [comment]
Thank you ! Great job.
Sorry for the delay... The changes are now live!
