### ISSUE TITLE
Play Store Device compatibility?

### ISSUE THREAD

**Issue by Fabien98** [OsmTravel/OsmGo#169]
It seems there is an issue on the Google play store.
The play store doesn't allow a new installation.
see capture below.

Tried on different recent devices with Android 12 or 13 installed.
![OSMGo compatibility](https://github.com/OsmTravel/OsmGo/assets/2730772/b2d317ef-5fa0-4e85-a179-febbb0030d55)

**Comment by timothywashere** [comment]
Can no longer launch app at all 😭 says " app isn't installed" even though it is

**Comment by DoFabien** [comment]
Hello, and thank you for the report.
I think they're 2 different problems.
Can you tell me if they were fixed in the last update?

**Comment by timothywashere** [comment]
My issue is fixed, thank you very much for the quick response!

**Comment by Fabien98** [comment]
As for me, its ok with last update, you can close. I was able to download the app on the Samsung device.
Thanks! 👍
