### ISSUE TITLE
[Bug] Drop-down selection comboboxes stopped working no longer displaying any content

### ISSUE THREAD

**Issue by bentolor** [OsmTravel/OsmGo#170]
Thanks for this great tool! I'm a long-term user of OSM Go! which encourages me to significantly contribute to OSM.

As of today suddenly (same device, same OS major version, same OSM Go!) comboboxes (i.e. yes/no) stopped working for me: Only a dimming appears, but no longer any content.

Multi-selection popups still work flawlessly?!

Anybody found a workaround for this?
  
![Screenshot-2023-08-05-17-26-12](https://github.com/OsmTravel/OsmGo/assets/588260/787e6865-be26-4b08-8aba-2edc9cad38e1)
![Screenshot-2023-08-05-17-27-30](https://github.com/OsmTravel/OsmGo/assets/588260/5cbc2927-ce1d-4716-b262-85bd1d837bac)

**Comment by timothywashere** [comment]
Same issue for me

**Comment by timothywashere** [comment]
Fixed for me in latest release !!

**Comment by DoFabien** [comment]
Yes, it was really strange, nothing had been modified.

**Comment by bentolor** [comment]
Thanks @DoFabien for the quick fix. As a way to contribute back, I translated the new missing entries for English and German on poeditor.com.
